### ISSUE TITLE
"Signature" (C-$) and "Selection-> Sections -> Subsubsection"  (C-S-4) conflict on a US keyboard.

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript-extra#24] opened 2021-12-10 17:21 UTC
The default bindings in quickscript-extra conflict: "Signature" (C-$) and "Selection-> Sections -> Subsubsection"  (C-S-4) conflict on a US keyboard.

**Comment by Metaxal** [comment] 2021-12-11 13:48
Thanks for the report!
Unfortunately that's non trivial to resolve: 
* if I change the keybinding some people will be rightfully unhappy of a change
* this depends largely on the keyboards (although UK+US are probably the most common, there's a good fraction of other layouts in the Racket community)

Shadow scripts are currently the best way to solve this, but I want something even simpler, like a GUI that lets the user choose the keybindings for each script with an event listener.

I'm keeping this open for now then. Other ideas welcome.

**Comment by spdegabrielle** [comment] 2021-12-13 00:32
I agree with everything, but as the vast majority of racketeers are using US keyboards, I think a pragmatic approach might be to find keybindings that work with us keyboards.
 
For keybindings UI, an approach I've seen before is a keybinding search, where you interactively select keybindings and it tells you if they are already allocated. The show active keybindings already searches on keybinding 'name' (notable that this is yet another implementation of the search-list-box design) - a "search-list-box" that supports searching on keybindings would be a useful complement. The difference in this case is the search-list-box is for keypresses, not character sequences.

https://docs.racket-lang.org/drracket/Keyboard_Shortcuts.html#%28part._defining-shortcuts%29

**Comment by spdegabrielle** [comment] 2021-12-13 00:47
> And finally, the **authoritative source for keybindings** is the Edit menu’s Show Active Keybindings menu item. Keybindings in DrRacket **are often sensitive to the window that has the keyboard focus**, so the contents of the window that Show Active Keybindings opens will depend where the keyboard focus was when the menu was selected.

ok that seems tricky.

**Comment by maueroats** [comment] 2021-12-13 23:29
Is Alt-$ available? It looks like it? That would keep the mnemonic of $ - S - Signature.

**Comment by spdegabrielle** [comment] 2021-12-14 13:13
@maueroats what platforms and keyboards do you use?

Alt-$ appears unbound on UK keyboards on both macOS and windows - in both cases the $ glyph is on the numeric 4 key.

I tested shifted and unshifted;   Alt-$ and Alt-4

macOS gives funny characters ›¢

**Comment by Metaxal** [comment] 2022-01-10 11:41
> I agree with everything, but as the vast majority of racketeers are using US keyboards, I think a pragmatic approach might be to find keybindings that work with us keyboards.

That seems too late now, as such a change would be backward incompatible, but it's something to keep in mind for future keybindings.

(Also, I'm "working" on a way to make changing keybindings much easier and should solve a lot of keybinding issues, but it's going slowly.)

**Comment by Metaxal** [comment] 2023-12-13 10:17
I'm closing this issue as it can be resolved (as intended) with shadow scripts. Feel free to reopen if something's not right.

**Closed as completed by Metaxal** 2023-12-13 10:17 UTC
