### ISSUE TITLE
Shadow scripts contain the version of Racket

### ISSUE THREAD

**Issue by maueroats** [Metaxal/quickscript-extra#31] opened 2024-11-25 14:13 UTC
I recently discovered that a shadow script contains a line the specific version of Racket in which it was created.  Note the **8.4** in the line below.

```
(require quickscript
         (prefix-in shadow: (file "/home/user/.local/share/racket/8.4/pkgs/quickscript-extra/scripts/sections.rkt")))
```

In this case, it was very surprising to me that deleting the Racket 8.4 files caused me to get errors on startup in Racket 8.15. Fortunately it was not hard to debug, so I suppose one should not spend too long fixing it.

If you don't have a better suggestion, consider including a warning in the documentation for shadow scripts. Generating a warning on first startup of a new version of Racket would be even better.

**Comment by Metaxal** [comment] 2024-11-25 20:52
Someone else than me uses shadow scripts! o_O

The problem is that shadowed scripts may be from package, or not. But this can't be straightforwardly found out just from calling the script unfortunately — I think. Though I do remember considering this at some point :thinking: 

Packages are not terribly well handle by Quickscript currently, I'm afraid. There's some [work in progress](https://github.com/Metaxal/quickscript/pull/81) though.

Would adding a line in the docs have helped you in this instance?

I'm not sure how to find out that DrRacket is started after an upgrade of the racket version.

**Comment by maueroats** [comment] 2024-11-26 00:45
> Packages are not terribly well handle by Quickscript currently, I'm afraid. There's some [work in progress](https://github.com/Metaxal/quickscript/pull/81) though.

I looked, but that's all. Thanks for the pointer. 

> Would adding a line in the docs have helped you in this instance?

No. It only took one more minute to find and fix the problem after reading that page (which otherwise did not help).

> I'm not sure how to find out that DrRacket is started after an upgrade of the racket version.

Somewhere the directory for quickscript-extra in (new version of Racket) is added to the Quickscript Directories. That would be one potential place for  "hook". I guess that happens during the package migration process, though. 

Maybe Quickscript installation could install a self-removing "first-run" flag (or script? or preference option?) that could be detected when the menu is built after installation. 

Thinking about this, Quickscript could check the directories for two different versions of Racket and issue a warning (or error, or offer to fix it automatically). If a hack like me did this check, it would find directories containing the string `$RACKET_VERSION` and then check to see if there were strings with other numbers in that place. Approached that way, this might be a "good first issue".

Seems like this might be overengineering a small inconvenience.

**Comment by Metaxal** [comment] 2024-11-27 14:38
I'm thinking that reporting a better error, along with giving the user potential ways to fix them might be a better approach in the short term.

This would avoid the potentially nasty and wrong 'automatic fixes' that we may guess could work, while at least being more helpful.

What error message would you have liked to see?

**Comment by maueroats** [comment] 2024-11-28 13:53
I cannot reproduce the problem. Maybe I didn't read the error message carefully enough the first time. The current error message is fine - perfectly informative.

I was going to say: a good error message would be something like: "script XXX at location FULLPATHNAME failed to load, throwing error: ORIGINAL ERROR", but the error message I get attempting to reproduce has this information.

I think the original error was triggered by a change in the configuration that did not cause a recompilation... but right now everything I try causes a recompilation, which generates a nice error.

OK to close unless you want to test more.

**Comment by Metaxal** [comment] 2024-11-28 16:06
Ok, great to hear. If you happen to find a way to reproduce your original error, let me know! I'm closing the issue for now.

**Closed as completed by Metaxal** 2024-11-28 16:06 UTC
